version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "http://mybucketfrontend.s3-website.eu-north-1.amazonaws.com/"
        BUILD_FOLDER: "dist/"
phases:
  install:
    runtime-versions:
        nodejs: 18
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '*/'
    base-directory: 'dist/product-community-site*'
    discard-paths: yes